### ISSUE TITLE
Naming error when applying pytential

### ISSUE THREAD

**Issue by benSepanski** [firedrakeproject/loopy#11]
I get the following error when I try to execute a pytential operator with `fmm_order=False`

```
/home/bensepan/inducer/pytential/pytential/symbolic/primitives.py:1571: UserWarning: specified the name of the direction vector
  return DirectionalSourceDerivative(
/home/bensepan/firedrake/lib/python3.9/site-packages/sumpy/kernel.py:1020: UserWarning: specified the name of the direction vector
  return type(kernel)(
Traceback (most recent call last):
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pytools/__init__.py", line 682, in wrapper
    return getattr(obj, cache_dict_name)[key]
AttributeError: 'PyOpenCLKernelExecutor' object has no attribute '_memoize_dic_program_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/run_trial.py", line 545, in <module>
    true_sol, comp_sol, snes_or_ksp = run_method.run_method(
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/methods/run_method.py", line 202, in run_method
    ksp, comp_sol = nonlocal_integral_eq(
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/methods/nonlocal_integral_eq.py", line 327, in nonlocal_integral_eq
    f_grad_convoluted_mm = rhs_grad_op(actx, sigma=true_sol_grad_mm, k=wave_number)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 1062, in __call__
    return self.eval(kwargs, array_context=array_context)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 1037, in eval
    return self.code.execute(exec_mapper)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/compiler.py", line 385, in execute
    self.get_exec_function(insn, exec_mapper)(
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 343, in exec_compute_potential_insn
    source.exec_compute_potential_insn(
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 458, in exec_compute_potential_insn
    return self._dispatch_compute_potential_insn(
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 520, in _dispatch_compute_potential_insn
    return func(actx, insn, bound_expr, evaluate, **extra_args)
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 808, in exec_compute_potential_insn_direct
    evt, output_for_each_kernel = p2p(queue,
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/sumpy/p2p.py", line 216, in __call__
    return knl(queue, sources=sources, targets=targets, strength=strength,
  File "/home/bensepan/firedrake/src/loopy/loopy/program.py", line 396, in __call__
    return pex(*args, **kwargs)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/pyopencl_execution.py", line 353, in __call__
    program_info = self.program_info(self.arg_to_dtype_set(kwargs))
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pytools/__init__.py", line 684, in wrapper
    result = function(obj, *args, **kwargs)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/pyopencl_execution.py", line 285, in program_info
    codegen_result = generate_code_v2(program)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/__init__.py", line 601, in generate_code_v2
    generate_code_for_a_single_kernel(in_knl_callable.subkernel,
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/__init__.py", line 524, in generate_code_for_a_single_kernel
    codegen_result = generate_host_or_device_program(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/result.py", line 293, in generate_host_or_device_program
    codegen_result = build_loop_nest(codegen_state, schedule_index)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 552, in build_loop_nest
    insn_group = build_insn_group(sched_index_info_entries, codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 545, in build_insn_group
    result = gen_code(new_codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 486, in gen_code
    inner = generate_code_for_sched_index(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 114, in generate_code_for_sched_index
    codegen_result = generate_host_or_device_program(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/result.py", line 288, in generate_host_or_device_program
    codegen_result = set_up_hw_parallel_loops(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/loop.py", line 336, in set_up_hw_parallel_loops
    inner = set_up_hw_parallel_loops(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/loop.py", line 253, in set_up_hw_parallel_loops
    return next_func(codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 552, in build_loop_nest
    insn_group = build_insn_group(sched_index_info_entries, codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 547, in build_insn_group
    return result + build_insn_group(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 545, in build_insn_group
    result = gen_code(new_codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 486, in gen_code
    inner = generate_code_for_sched_index(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 158, in generate_code_for_sched_index
    return func(codegen_state, sched_index)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/loop.py", line 441, in generate_sequential_loop_dim_code
    inner = build_loop_nest(new_codegen_state, sched_index+1)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 552, in build_loop_nest
    insn_group = build_insn_group(sched_index_info_entries, codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 547, in build_insn_group
    return result + build_insn_group(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 545, in build_insn_group
    result = gen_code(new_codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 486, in gen_code
    inner = generate_code_for_sched_index(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 158, in generate_code_for_sched_index
    return func(codegen_state, sched_index)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/loop.py", line 441, in generate_sequential_loop_dim_code
    inner = build_loop_nest(new_codegen_state, sched_index+1)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 552, in build_loop_nest
    insn_group = build_insn_group(sched_index_info_entries, codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 547, in build_insn_group
    return result + build_insn_group(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 545, in build_insn_group
    result = gen_code(new_codegen_state)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 486, in gen_code
    inner = generate_code_for_sched_index(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 198, in generate_code_for_sched_index
    return codegen_state.try_vectorized(
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/__init__.py", line 342, in try_vectorized
    return func(self)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/control.py", line 200, in <lambda>
    lambda inner_cgs: generate_instruction_code(inner_cgs, insn))
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/instruction.py", line 83, in generate_instruction_code
    ast = generate_assignment_instruction_code(codegen_state, insn)
  File "/home/bensepan/firedrake/src/loopy/loopy/codegen/instruction.py", line 157, in generate_assignment_instruction_code
    result = codegen_state.ast_builder.emit_assignment(codegen_state, insn)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/c/__init__.py", line 960, in emit_assignment
    ecm(insn.expression, prec=PREC_NONE,
  File "/home/bensepan/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 115, in __call__
    self.rec(expr, type_context, needed_dtype))
  File "/home/bensepan/firedrake/src/loopy/loopy/target/c/codegen/expression.py", line 105, in rec
    RecursiveMapper.rec(self, expr, type_context))
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pymbolic/mapper/__init__.py", line 134, in __call__
    return method(expr, *args, **kwargs)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/opencl.py", line 468, in map_product
    real_prd = p.flattened_product(
NameError: name 'p' is not defined
```

**Comment by inducer** [comment]
@kaushikcfd Could you take a quick look?

**Comment by benSepanski** [comment]
Just realizing this is on my fork of loopy which is a bit behind. Let me see if I can fix it by merging in the upstream changes

**Comment by benSepanski** [comment]
Okay, I'm still getting the same error on the same line

**Comment by kaushikcfd** [comment]
Needs  a `import pymbolic.primitives as p` a the top, along with Ben's changes at https://github.com/firedrakeproject/loopy/pull/8.

**Comment by benSepanski** [comment]
With those changes, I'm hitting 
```
4 errors generated.
Traceback (most recent call last):
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pytools/__init__.py", line 682, in wrapper
    return getattr(obj, cache_dict_name)[key]
AttributeError: 'PyOpenCLKernelExecutor' object has no attribute '_memoize_dic_program_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/run_trial.py", line 546, in <module>
    true_sol, comp_sol, snes_or_ksp = run_method.run_method(
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/methods/run_method.py", line 202, in run_method
    ksp, comp_sol = nonlocal_integral_eq(
  File "/home/bensepan/nonlocal-firedrake-examples/HelmholtzSommerfeldProblem/methods/nonlocal_integral_eq.py", line 327, in nonlocal_integral_eq
    f_grad_convoluted_mm = rhs_grad_op(actx, sigma=true_sol_grad_mm, k=wave_number)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 1062, in __call__
    return self.eval(kwargs, array_context=array_context)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 1037, in eval
    return self.code.execute(exec_mapper)
  File "/home/bensepan/inducer/pytential/pytential/symbolic/compiler.py", line 385, in execute
    self.get_exec_function(insn, exec_mapper)(
  File "/home/bensepan/inducer/pytential/pytential/symbolic/execution.py", line 343, in exec_compute_potential_insn
    source.exec_compute_potential_insn(
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 458, in exec_compute_potential_insn
    return self._dispatch_compute_potential_insn(
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 520, in _dispatch_compute_potential_insn
    return func(actx, insn, bound_expr, evaluate, **extra_args)
  File "/home/bensepan/inducer/pytential/pytential/qbx/__init__.py", line 808, in exec_compute_potential_insn_direct
    evt, output_for_each_kernel = p2p(queue,
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/sumpy/p2p.py", line 216, in __call__
    return knl(queue, sources=sources, targets=targets, strength=strength,
  File "/home/bensepan/firedrake/src/loopy/loopy/program.py", line 396, in __call__
    return pex(*args, **kwargs)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/pyopencl_execution.py", line 353, in __call__
    program_info = self.program_info(self.arg_to_dtype_set(kwargs))
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pytools/__init__.py", line 684, in wrapper
    result = function(obj, *args, **kwargs)
  File "/home/bensepan/firedrake/src/loopy/loopy/target/pyopencl_execution.py", line 307, in program_info
    cl.Program(self.context, dev_code)
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pyopencl/__init__.py", line 537, in build
    self._prg, was_cached = self._build_and_catch_errors(
  File "/home/bensepan/firedrake/lib/python3.9/site-packages/pyopencl/__init__.py", line 585, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'pthread-Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz' on 'Portable Computing Language' at 0x1532020>:

error: /home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:75:19 <Spelling=/home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:75:38>: use of undeclared identifier '_Complex_I'
error: /home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:75:19 <Spelling=/home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:75:38>: use of undeclared identifier '_Complex_I'
error: /home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:76:19 <Spelling=/home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:76:38>: use of undeclared identifier '_Complex_I'
error: /home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:76:19 <Spelling=/home/bensepan/.cache/pocl/kcache/tempfile-f5-53-99-7c-62.cl:76:38>: use of undeclared identifier '_Complex_I'
```

**Comment by kaushikcfd** [comment]
Looks like some error were picked up into the opencl target during the complex merge. Looking into fixing those.

**Comment by inducer** [comment]
This is probably resolved, now that everybody is on the same loopy branch.
